version: "3.8"

services:
  app:
    container_name: code-editor
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      
    ports:
      - 5000:5000
